// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logSumExp
double logSumExp(const arma::rowvec& x);
RcppExport SEXP _cyclinbayes_logSumExp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp(x));
    return rcpp_result_gen;
END_RCPP
}
// log_dgamma
double log_dgamma(double x, double a, double b);
RcppExport SEXP _cyclinbayes_log_dgamma(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(log_dgamma(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// BayesSCLingam_cpp
List BayesSCLingam_cpp(arma::mat data_matrix, double a_mu, double b_mu, double a_gamma, double b_gamma, double a_tao, double b_tao, double a_og_tao, double b_og_tao, double a_gamma_1, double b_gamma_1, double alpha, double M, double num_iter);
RcppExport SEXP _cyclinbayes_BayesSCLingam_cpp(SEXP data_matrixSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP a_taoSEXP, SEXP b_taoSEXP, SEXP a_og_taoSEXP, SEXP b_og_taoSEXP, SEXP a_gamma_1SEXP, SEXP b_gamma_1SEXP, SEXP alphaSEXP, SEXP MSEXP, SEXP num_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data_matrix(data_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< double >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tao(a_taoSEXP);
    Rcpp::traits::input_parameter< double >::type b_tao(b_taoSEXP);
    Rcpp::traits::input_parameter< double >::type a_og_tao(a_og_taoSEXP);
    Rcpp::traits::input_parameter< double >::type b_og_tao(b_og_taoSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma_1(a_gamma_1SEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma_1(b_gamma_1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type num_iter(num_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(BayesSCLingam_cpp(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter));
    return rcpp_result_gen;
END_RCPP
}
// BCD_cpp
List BCD_cpp(arma::mat data_matrix, double a_mu, double b_mu, double a_gamma, double b_gamma, double a_tao, double b_tao, double a_gamma_1, double b_gamma_1, double alpha, double M, double num_iter);
RcppExport SEXP _cyclinbayes_BCD_cpp(SEXP data_matrixSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP a_taoSEXP, SEXP b_taoSEXP, SEXP a_gamma_1SEXP, SEXP b_gamma_1SEXP, SEXP alphaSEXP, SEXP MSEXP, SEXP num_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data_matrix(data_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< double >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tao(a_taoSEXP);
    Rcpp::traits::input_parameter< double >::type b_tao(b_taoSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma_1(a_gamma_1SEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma_1(b_gamma_1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type num_iter(num_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(BCD_cpp(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cyclinbayes_logSumExp", (DL_FUNC) &_cyclinbayes_logSumExp, 1},
    {"_cyclinbayes_log_dgamma", (DL_FUNC) &_cyclinbayes_log_dgamma, 3},
    {"_cyclinbayes_BayesSCLingam_cpp", (DL_FUNC) &_cyclinbayes_BayesSCLingam_cpp, 14},
    {"_cyclinbayes_BCD_cpp", (DL_FUNC) &_cyclinbayes_BCD_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_cyclinbayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
