# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logSumExp <- function(x) {
    .Call(`_cyclinbayes_logSumExp`, x)
}

log_dgamma <- function(x, a, b) {
    .Call(`_cyclinbayes_log_dgamma`, x, a, b)
}

BayesSCLingam_cpp <- function(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter) {
    .Call(`_cyclinbayes_BayesSCLingam_cpp`, data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter)
}

BCD_cpp <- function(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter) {
    .Call(`_cyclinbayes_BCD_cpp`, data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter)
}

