# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdirichlet_cpp <- function(alpha) {
    .Call(`_cyclinbayesrev_rdirichlet_cpp`, alpha)
}

rinvgamma_cpp <- function(n, shape, scale) {
    .Call(`_cyclinbayesrev_rinvgamma_cpp`, n, shape, scale)
}

logSumExp_v2 <- function(x) {
    .Call(`_cyclinbayesrev_logSumExp`, x)
}

log_dgamma_v2 <- function(x, a, b) {
    .Call(`_cyclinbayesrev_log_dgamma`, x, a, b)
}

mu_fun <- function(Z_matrix, a_mu, b_mu, tao_mat, epsilon_mat, num_covariates, M, N) {
    .Call(`_cyclinbayesrev_mu_fun`, Z_matrix, a_mu, b_mu, tao_mat, epsilon_mat, num_covariates, M, N)
}

tao_fun <- function(Z_matrix, a_tao, b_tao, mu_mat, epsilon_mat, num_covariates, M, N) {
    .Call(`_cyclinbayesrev_tao_fun`, Z_matrix, a_tao, b_tao, mu_mat, epsilon_mat, num_covariates, M, N)
}

pi_fun <- function(Z_matrix, num_covariates, alpha, K, N) {
    .Call(`_cyclinbayesrev_pi_fun`, Z_matrix, num_covariates, alpha, K, N)
}

Z_matrix_fun <- function(Z_matrix_1, epsilon_mat, mu_mat, tao_mat, pi_mat, num_covariates, N, M) {
    .Call(`_cyclinbayesrev_Z_matrix_fun`, Z_matrix_1, epsilon_mat, mu_mat, tao_mat, pi_mat, num_covariates, N, M)
}

is_dag <- function(adj) {
    .Call(`_cyclinbayesrev_is_dag`, adj)
}

Metropolis_hastings_portions_cpp <- function(data_matrix, Adjacency_matrix_enter, Causal_effect_matrix_enter, Z_matrix_enter, mu_mat, tao_mat, N, M, gamma_1, gamma_result) {
    .Call(`_cyclinbayesrev_Metropolis_hastings_portions_Z_cpp`, data_matrix, Adjacency_matrix_enter, Causal_effect_matrix_enter, Z_matrix_enter, mu_mat, tao_mat, N, M, gamma_1, gamma_result)
}

score_state_v2_cpp <- function(data_matrix, Adjacency_matrix, Causal_effect_matrix, Z_matrix, mu_mat, tao_mat, gamma_1, gamma_result) {
    .Call(`_cyclinbayesrev_score_state_cpp`, data_matrix, Adjacency_matrix, Causal_effect_matrix, Z_matrix, mu_mat, tao_mat, gamma_1, gamma_result)
}

BayesSCLingam_cpp <- function(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter, init_Adjacency = NULL, init_Causal_effect = NULL, init_mu = NULL, init_tao = NULL, init_pi = NULL, init_Z = NULL, init_gamma_1 = NULL, init_gamma_result = NULL) {
    .Call(`_cyclinbayesrev_BayesSCLingam_cpp`, data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter, init_Adjacency, init_Causal_effect, init_mu, init_tao, init_pi, init_Z, init_gamma_1, init_gamma_result)
}

project_to_disjoint_cycle_space_cpp <- function(Adj, B, max_steps = 10000L, stability_target = 0.95, verbose = TRUE) {
    .Call(`_cyclinbayesrev_project_to_disjoint_cycle_space_cpp`, Adj, B, max_steps, stability_target, verbose)
}

has_disjoint_cycles_cpp <- function(Adj) {
    .Call(`_cyclinbayesrev_has_disjoint_cycles_cpp`, Adj)
}

get_sccs_cpp <- function(Adj) {
    .Call(`_cyclinbayesrev_get_sccs_cpp`, Adj)
}

BCD_v2_two_phase_cpp <- function(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter, burn_in_iterations = 70000, init_Adjacency = NULL, init_Causal_effect = NULL, init_mu = NULL, init_tao = NULL, init_pi = NULL, init_Z = NULL, init_gamma_1 = NULL, init_gamma_result = NULL) {
    .Call(`_cyclinbayesrev_BCD_cpp`, data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter, burn_in_iterations, init_Adjacency, init_Causal_effect, init_mu, init_tao, init_pi, init_Z, init_gamma_1, init_gamma_result)
}

